// Ambient types for the Workers runtime.
//
// `worker-configuration.d.ts` is generated by `wrangler types` from the prepare
// script and lives at the repo root, which is outside the include list
// SvelteKit generates — so it has to be pulled in from inside src/ to be seen.
//
// A path reference is the only way in: the file declares globals and exports
// nothing, so there is no import form to prefer over it.
/* eslint-disable-next-line @typescript-eslint/triple-slash-reference */
/// <reference path="../worker-configuration.d.ts" />

// `cloudflare:test`, used by *.workers.spec.ts. The pool ships the types but
// only exposes them under an explicit reference.
/// <reference types="@cloudflare/vitest-pool-workers/types" />

// The bindings from wrangler.jsonc, declared by hand rather than generated.
//
// `wrangler types` will emit these, but its generated form also declares
// `Cloudflare.GlobalProps.mainModule` as an import of the built worker, which
// drags .svelte-kit/cloudflare/_worker.js into the typecheck: several hundred
// errors in generated output, and a `pnpm check` that only passes after a
// build. So the runtime types are generated with `--include-env=false` and the
// few lines that actually matter live here, where they are checked against use.
declare global {
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
	}

	namespace Cloudflare {
		interface Env {
			DB: D1Database;
			ASSETS: Fetcher;
		}
	}
}

export {};
